# Generated by Django 5.2.17 on 2026-09-05 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待判定'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已撤回'), ('completed', '已完成')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('author_confirmed', models.BooleanField(default=False, verbose_name='拾取者已确认')),
                ('claimant_confirmed', models.BooleanField(default=False, verbose_name='失主已确认')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='通过时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='失主')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='posts.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '认领',
                'verbose_name_plural': '认领',
                'db_table': 'claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='问题')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_questions', to='posts.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '隐藏特征问题',
                'verbose_name_plural': '隐藏特征问题',
                'db_table': 'claim_questions',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='claims.claim', verbose_name='认领')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='claims.claimquestion', verbose_name='问题')),
            ],
            options={
                'verbose_name': '认领回答',
                'verbose_name_plural': '认领回答',
                'db_table': 'claim_answers',
            },
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('post',), name='unique_active_claim_per_post'),
        ),
    ]
