"""AI 匹配常量。向量模型与 demo 对齐，排序权重取自技术路径大纲。"""

PROVIDER_DASHSCOPE = "dashscope"
PROVIDER_FAKE = "fake"

MODEL_DASHSCOPE = "tongyi-embedding-vision-flash-2026-03-06"
EMBEDDING_DIM = 512
EMBEDDING_VERSION = "v1"

STATUS_PENDING = "pending"
STATUS_READY = "ready"
STATUS_FAILED = "failed"

EMBEDDING_STATUS_CHOICES = [
    (STATUS_PENDING, "待处理"),
    (STATUS_READY, "已就绪"),
    (STATUS_FAILED, "失败"),
]

FEEDBACK_NONE = ""
FEEDBACK_NOT_MATCH = "not_match"

FEEDBACK_CHOICES = [
    (FEEDBACK_NONE, "无"),
    (FEEDBACK_NOT_MATCH, "不是这个"),
]

# 大纲 §5.5 初始权重，上线前不调参，不宣传成概率。
WEIGHT_VECTOR = 0.55
WEIGHT_CATEGORY_L2 = 0.15
WEIGHT_TIME = 0.10
WEIGHT_PLACE = 0.10
WEIGHT_ATTR = 0.10

DEFAULT_TIME_BEFORE_DAYS = 1
DEFAULT_TIME_AFTER_DAYS = 30

HARD_FILTER_CAP = 200
MATCH_STORE_LIMIT = 50
QUERY_EMBED_CACHE_TTL = 3600
ORIGINAL_GET_EXPIRES = 3600

VECTOR_REASON_THRESHOLD = 0.4
TIME_REASON_THRESHOLD = 0.5
