# Generated by Django 5.2.17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", models.JSONField(blank=True, null=True, verbose_name="向量")),
                (
                    "provider",
                    models.CharField(
                        default="dashscope", max_length=32, verbose_name="供应商"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="tongyi-embedding-vision-flash-2026-03-06",
                        max_length=128,
                        verbose_name="模型",
                    ),
                ),
                (
                    "dim",
                    models.PositiveSmallIntegerField(default=512, verbose_name="维度"),
                ),
                (
                    "version",
                    models.CharField(default="v1", max_length=16, verbose_name="版本"),
                ),
                (
                    "source_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="源指纹"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("ready", "已就绪"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="错误")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="posts.post",
                        verbose_name="帖子",
                    ),
                ),
                (
                    "post_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="posts.postimage",
                        verbose_name="帖子图片",
                    ),
                ),
            ],
            options={
                "verbose_name": "图片向量",
                "verbose_name_plural": "图片向量",
                "db_table": "image_embeddings",
            },
        ),
        migrations.CreateModel(
            name="MatchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="综合分")),
                ("vector_score", models.FloatField(default=0, verbose_name="向量分")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="匹配理由"),
                ),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        choices=[("", "无"), ("not_match", "不是这个")],
                        default="",
                        max_length=16,
                        verbose_name="用户反馈",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "candidate_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_matches",
                        to="posts.post",
                        verbose_name="候选帖",
                    ),
                ),
                (
                    "query_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_matches",
                        to="posts.post",
                        verbose_name="源帖",
                    ),
                ),
                (
                    "searcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_searches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="搜寻者",
                    ),
                ),
            ],
            options={
                "verbose_name": "匹配候选",
                "verbose_name_plural": "匹配候选",
                "db_table": "match_candidates",
                "ordering": ["-score", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="imageembedding",
            index=models.Index(
                fields=["status", "version"], name="emb_status_version_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imageembedding",
            index=models.Index(fields=["post", "status"], name="emb_post_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="imageembedding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post_image__isnull", False)),
                fields=("post_image", "provider", "model", "dim", "version"),
                name="uniq_embedding_per_image_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageembedding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post_image__isnull", True)),
                fields=("post", "provider", "model", "dim", "version"),
                name="uniq_text_embedding_per_post_version",
            ),
        ),
        migrations.AddIndex(
            model_name="matchcandidate",
            index=models.Index(
                fields=["query_post", "-score"], name="match_query_score_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchcandidate",
            index=models.Index(
                fields=["searcher", "-created_at"], name="match_searcher_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchcandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("query_post__isnull", False)),
                fields=("searcher", "query_post", "candidate_post"),
                name="uniq_match_per_query_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchcandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("query_post__isnull", True)),
                fields=("searcher", "candidate_post"),
                name="uniq_adhoc_match_per_searcher_candidate",
            ),
        ),
    ]
