# Generated by Django 5.2.17 on 2026-08-19 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='场所名称')),
                ('place_type', models.CharField(choices=[('school', '学校'), ('mall', '商场'), ('station', '车站'), ('park', '公园'), ('community', '社区'), ('office', '办公场所'), ('other', '其他')], default='other', max_length=32, verbose_name='场所类型')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '场所',
                'verbose_name_plural': '场所',
                'db_table': 'places',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lost', '丢失'), ('found', '捡到')], max_length=16, verbose_name='类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('claiming', '认领中'), ('completed', '已完成'), ('closed', '已关闭')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('category_l1', models.CharField(choices=[('electronics', '电子设备'), ('documents', '证件'), ('bags', '包袋'), ('clothing', '衣物'), ('accessories', '饰品'), ('stationery', '文具'), ('keys', '钥匙与门禁'), ('other', '其他')], db_index=True, max_length=32, verbose_name='一级分类')),
                ('category_l2', models.CharField(choices=[('phone', '手机'), ('laptop', '笔记本电脑'), ('tablet', '平板'), ('headphones', '耳机'), ('other_electronics', '其他电子设备'), ('id_card', '身份证'), ('student_id', '学生证'), ('bank_card', '银行卡'), ('driver_license', '驾驶证'), ('other_documents', '其他证件'), ('backpack', '双肩包'), ('wallet', '钱包'), ('handbag', '手提包'), ('other_bags', '其他包袋'), ('jacket', '外套'), ('scarf', '围巾'), ('other_clothing', '其他衣物'), ('watch', '手表'), ('glasses', '眼镜'), ('jewelry', '首饰'), ('other_accessories', '其他饰品'), ('book', '书籍'), ('stationery_box', '文具盒'), ('other_stationery', '其他文具'), ('keys', '钥匙'), ('access_card', '门禁卡'), ('other_keys', '其他钥匙/门禁'), ('other', '其他')], max_length=32, verbose_name='二级分类')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('found_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='发现纬度')),
                ('found_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='发现经度')),
                ('custody_type', models.CharField(choices=[('personal', '个人保管'), ('official', '官方保管')], default='personal', max_length=16, verbose_name='保管方式')),
                ('custody_address', models.CharField(blank=True, max_length=255, verbose_name='保管地址')),
                ('event_start_at', models.DateTimeField(verbose_name='时间窗口起点')),
                ('event_end_at', models.DateTimeField(verbose_name='时间窗口终点')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('custody_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_posts', to='posts.place', verbose_name='保管场所')),
                ('found_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_posts', to='posts.place', verbose_name='发现场所')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=64, verbose_name='品牌')),
                ('primary_color', models.CharField(blank=True, max_length=64, verbose_name='主色')),
                ('text_mark', models.CharField(blank=True, max_length=128, verbose_name='文字标识')),
                ('distinctive_features', models.TextField(blank=True, verbose_name='显著特征')),
                ('normalized_description', models.TextField(blank=True, verbose_name='规范化描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='posts.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '帖子结构化属性',
                'verbose_name_plural': '帖子结构化属性',
                'db_table': 'post_attributes',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos_key', models.CharField(max_length=512, verbose_name='对象存储键')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='顺序')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '拒绝')], db_index=True, default='pending', max_length=16, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '帖子图片',
                'verbose_name_plural': '帖子图片',
                'db_table': 'post_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='行政区代码')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('level', models.CharField(choices=[('province', '省'), ('city', '市'), ('district', '区/县')], max_length=16, verbose_name='级别')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='posts.region', verbose_name='上级行政区')),
            ],
            options={
                'verbose_name': '行政区',
                'verbose_name_plural': '行政区',
                'db_table': 'regions',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='found_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='found_posts', to='posts.region', verbose_name='发现行政区'),
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='posts.region', verbose_name='所属行政区'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['type', 'status'], name='post_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category_l1', 'status'], name='post_cat1_status_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['event_start_at', 'event_end_at'], name='post_event_idx'),
        ),
    ]
